### ISSUE TITLE
Missing radar codes in OPERA database

### ISSUE THREAD

**Issue by peterdesmet** [aloftdata/registry#12]
Radars to be added to OPERA DB (see table below for more info):

- [x] behel
- [x] debln
- [x] deflg (see enram/registry#21)
- [x] deham
- [x] dehan
- [x] demhp: not in coverage.csv
- [x] demuc
- [x] desna  (see enram/registry#21)
- [x] eesur (not eesyr)
- [x] nlhrw (no space)
- [x] seatv
- [x] sebaa
- [x] sehem
- [x] sehud (see enram/registry#23)
- [x] sekaa
- [x] sekrn
- [x] sella
- [x] seoer
- [x] seosu (see enram/registry#23)
- [x] sevar

The following radar codes are in use (situation 11 sep 2019), but are not listed in the [OPERA database](https://github.com/enram/globam-dmp/blob/master/data/OPERA_RADARS_DB.json):

radar | baltrad pvol | status | remarks | suggested action for OPERA
--- | --- | --- | --- | ---
behel | 2018-2019 | active | enram/data-repository#92 | add to DB
bgvar | - | ? | flyway only | no action
ctcdv | - | ? | flyway only | no action
ctpda | - | ? | flyway only | no action
debln | 2012-2014 | inactive | | add to DB
deflg | 2012-2018 | inactive | #2 | add to DB
deham | 2012-2014 | inactive | | add to DB
dehan | 2012-2014 | inactive | | add to DB
demhp | 2018-2018 | inactive | | add to DB
demuc | 2013-2014 | inactive | | add to DB
desna | 2014-2019 | inactive | stopped in 2019-04-04 enram/registry#4 | add to DB
eesur | 2012-2019 | active | eesyr exists in DB | update code in DB
frrem | 2019 | ? | not much data, artefact? | 
istgb | - | ? | found on ftp.baltrad.eu only | 
nlhrw | 2017-2019 | active | written with space in opera DB enram/registry#9 | remove space in code 
ptliz | - | ? | flyway only, should probably be written as ptlis | no action
seatv | 2019 | active | replaces sevil enram/registry#7 | add to DB
sebaa | 2019 | active | kinda replaces searl? enram/registry#7 | add to DB
sehem | 2017-2019 | active | replaces sease enram/registry#7 | add to DB
sehud | 2012-2016 | inactive | replaced by sehuv enram/registry#7 | add to DB
sekaa | 2018-2019 | active | replaces sekkr enram/registry#7 | add to DB
sekrn | - | ? | supposedly replaces sekir enram/registry#7 | add to DB
sella | 2018-2019 | active | replaces selul enram/registry#7 | add to DB
seoer | 2017-2019 | active | replaces seovi enram/registry#7 | add to DB
seosu | 2012-2016 | inactive | replaced by seosd enram/registry#7 | add to DB
sevar | 2012-2016 | inactive | replaced by seosd enram/registry#7 | add to DB

@leijnse how can we suggest changes to the OPERA database? Also, would it be possible to add the property `replacedBy` to the database, to indicate code changes (e.g. for Sweden)?

**Comment by peterdesmet** [comment]
@leijnse @BarVodSur see also enram/registry#13 on merging with the radar archive. Can I suggest to add the radars in the checklist above to the OPERA DB (active and inactive ones)? And (especially for cases like the Swedish radars) have a `replacedby` property?

**Comment by peterdesmet** [comment]
All the above issues are either resolved or reported in separate issues. Closing this issue.

**Comment by BarVodSur** [comment]
Dear Peter,

 

Only country reperentatives can add radars to our database. 

 

BR,

Barbara 

 



 

From: Peter Desmet ***@***.***> 
Sent: Wednesday, November 13, 2024 10:39 AM
To: enram/registry ***@***.***>
Cc: Barbara Vodaric Surija ***@***.***>; Assign ***@***.***>
Subject: [enram/registry] Missing radar codes in OPERA database (#12)

 

Radars to be added to OPERA DB (see table below for more info):

*	[X] behel
*	[X] debln
*	[X] deflg (see enram/data-repository#105 <https://github.com/enram/data-repository/issues/105> )
*	[X] deham
*	[X] dehan
*	[X] demhp: not in coverage.csv
*	[X] demuc
*	[X] desna (see enram/data-repository#105 <https://github.com/enram/data-repository/issues/105> )
*	[X] eesur (not eesyr)
*	[X] nlhrw (no space)
*	[X] seatv
*	[X] sebaa
*	[X] sehem
*	[X] sehud (see enram/data-repository#103 <https://github.com/enram/data-repository/issues/103> )
*	[X] sekaa
*	[X] sekrn
*	[X] sella
*	[X] seoer
*	[X] seosu (see enram/data-repository#103 <https://github.com/enram/data-repository/issues/103> )
*	[X] sevar

The following radar codes are in use (situation 11 sep 2019), but are not listed in the OPERA database <https://github.com/enram/globam-dmp/blob/master/data/OPERA_RADARS_DB.json> :


radar

baltrad pvol

status

remarks

suggested action for OPERA


behel

2018-2019

active

enram/data-repository#92 <https://github.com/enram/data-repository/issues/92> 

add to DB


bgvar

-

?

flyway only

no action


ctcdv

-

?

flyway only

no action


ctpda

 -

?

flyway only

no action


debln

2012-2014

 inactive

 

add to DB


deflg

2012-2018

 inactive

 #2 <https://github.com/enram/registry/issues/2> 

add to DB


deham

2012-2014

 inactive

 

add to DB


dehan

2012-2014

 inactive

 

add to DB


demhp

2018-2018

 inactive

 

add to DB


demuc

2013-2014

 inactive

	add to DB


desna

2014-2019

 inactive

 stopped in 2019-04-04 #4 <https://github.com/enram/registry/issues/4> 

 add to DB


eesur

2012-2019

active

eesyr exists in DB

update code in DB


frrem

 2019

 ?

not much data, artefact?

	

istgb

 -

?

found on ftp.baltrad.eu <ftp://ftp.baltrad.eu>  only

	

nlhrw

2017-2019

active

written with space in opera DB #9 <https://github.com/enram/registry/issues/9> 

remove space in code


ptliz

-

?

 flyway only, should probably be written as ptlis

no action


seatv

2019

active

replaces sevil #7 <https://github.com/enram/registry/issues/7> 

add to DB


sebaa

2019

active

kinda replaces searl? #7 <https://github.com/enram/registry/issues/7> 

 add to DB


sehem

2017-2019

 active

replaces sease #7 <https://github.com/enram/registry/issues/7> 

add to DB


sehud

2012-2016

 inactive

replaced by sehuv #7 <https://github.com/enram/registry/issues/7> 

add to DB


sekaa

2018-2019

active

replaces sekkr #7 <https://github.com/enram/registry/issues/7> 

add to DB


sekrn

-

?

supposedly replaces sekir #7 <https://github.com/enram/registry/issues/7> 

add to DB


sella

2018-2019

active

replaces selul #7 <https://github.com/enram/registry/issues/7> 

add to DB


seoer

2017-2019

active

replaces seovi #7 <https://github.com/enram/registry/issues/7> 

add to DB


seosu

2012-2016

inactive

 replaced by seosd #7 <https://github.com/enram/registry/issues/7> 

add to DB


sevar

2012-2016

inactive

 replaced by seosd #7 <https://github.com/enram/registry/issues/7> 

add to DB

@leijnse <https://github.com/leijnse>  how can we suggest changes to the OPERA database? Also, would it be possible to add the property replacedBy to the database, to indicate code changes (e.g. for Sweden)?
